/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
public class BOOK extends javax.swing.JFrame {

    /**
     * Creates new form BOOK
     */
    public BOOK() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        blocation = new javax.swing.JLabel();
        bdestination = new javax.swing.JLabel();
        btime = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        bnext = new javax.swing.JButton();
        bhome = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 51));
        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("THANK YOU FOR CHOOSING US, PLEASE CHOOSE YOUR FAVORITE BUS!");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 784, 38));

        blocation.setBackground(new java.awt.Color(51, 255, 51));
        blocation.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        blocation.setForeground(new java.awt.Color(255, 255, 255));
        blocation.setText("Enter Your Location");
        getContentPane().add(blocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 124, 173, 53));

        bdestination.setBackground(new java.awt.Color(255, 255, 51));
        bdestination.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        bdestination.setForeground(new java.awt.Color(255, 255, 255));
        bdestination.setText("Enter Your Destination");
        getContentPane().add(bdestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 243, -1, 42));

        btime.setBackground(new java.awt.Color(255, 102, 51));
        btime.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btime.setForeground(new java.awt.Color(255, 255, 255));
        btime.setText("DATE");
        getContentPane().add(btime, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 319, 173, 66));

        jScrollPane1.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 141, 220, 41));

        jScrollPane2.setViewportView(jTextPane2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 243, 220, 42));

        jScrollPane3.setViewportView(jTextPane3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 319, 220, 66));

        bnext.setBackground(new java.awt.Color(255, 255, 51));
        bnext.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        bnext.setText("NEXT");
        bnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnextActionPerformed(evt);
            }
        });
        getContentPane().add(bnext, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 430, 93, -1));

        bhome.setBackground(new java.awt.Color(51, 255, 51));
        bhome.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        bhome.setText("HOME");
        bhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhomeActionPerformed(evt);
            }
        });
        getContentPane().add(bhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(921, 24, 110, 38));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot 2024-01-26 141355.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 1020, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhomeActionPerformed
        // TODO add your handling code here:
        dispose ();
        HOME b=new HOME ();
        b.show();
    }//GEN-LAST:event_bhomeActionPerformed

    private void bnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnextActionPerformed
        // TODO add your handling code here:
        dispose ();
        SEAT v=new SEAT ();
        v.show();
    }//GEN-LAST:event_bnextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BOOK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BOOK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BOOK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BOOK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BOOK().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bdestination;
    private javax.swing.JButton bhome;
    private javax.swing.JLabel blocation;
    private javax.swing.JButton bnext;
    private javax.swing.JLabel btime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    // End of variables declaration//GEN-END:variables
}
