/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
public class HOME extends javax.swing.JFrame {

    /**
     * Creates new form HOME
     */
    public HOME() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        hhome = new javax.swing.JButton();
        hservice = new javax.swing.JButton();
        hbus = new javax.swing.JButton();
        hbook = new javax.swing.JButton();
        habout = new javax.swing.JButton();
        hrefund = new javax.swing.JButton();
        haccount = new javax.swing.JButton();
        rlogout = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 255, 51));

        jLabel1.setBackground(new java.awt.Color(153, 255, 51));
        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("UMURAGWA ONLINE BUS BOOKING");
        jLabel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jLabel1.setMaximumSize(new java.awt.Dimension(1000, 78));

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 902, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 934, 97));

        hhome.setBackground(new java.awt.Color(255, 255, 0));
        hhome.setText("HOME");
        hhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hhomeActionPerformed(evt);
            }
        });
        getContentPane().add(hhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 135, 163, 51));

        hservice.setBackground(new java.awt.Color(255, 255, 0));
        hservice.setText("OUR SERVICES");
        hservice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hserviceActionPerformed(evt);
            }
        });
        getContentPane().add(hservice, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 225, 163, 47));

        hbus.setBackground(new java.awt.Color(255, 255, 0));
        hbus.setText("HELP");
        getContentPane().add(hbus, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 532, 163, 50));

        hbook.setBackground(new java.awt.Color(255, 255, 0));
        hbook.setText("BOOK A BUS");
        hbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hbookActionPerformed(evt);
            }
        });
        getContentPane().add(hbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 306, 163, 47));

        habout.setBackground(new java.awt.Color(255, 255, 0));
        habout.setText("ABOUT US");
        habout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                haboutActionPerformed(evt);
            }
        });
        getContentPane().add(habout, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 461, 163, 47));

        hrefund.setBackground(new java.awt.Color(255, 255, 0));
        hrefund.setText("REFUND PROCESS");
        getContentPane().add(hrefund, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 387, 163, 44));

        haccount.setBackground(new java.awt.Color(255, 255, 51));
        haccount.setText("MANAGE MY ACCOUNT");
        haccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                haccountActionPerformed(evt);
            }
        });
        getContentPane().add(haccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 526, 197, 61));

        rlogout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rlogout.setText("LOGOUT");
        rlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rlogoutActionPerformed(evt);
            }
        });
        getContentPane().add(rlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 550, 110, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot 2024-01-26 141355.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hserviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hserviceActionPerformed
        // TODO add your handling code here:
        dispose ();
        SERVICES s=new SERVICES ();
        s.show();
    }//GEN-LAST:event_hserviceActionPerformed

    private void hhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hhomeActionPerformed
        // TODO add your handling code here:
        dispose ();
        HOME h= new HOME ();
        h.show();
    }//GEN-LAST:event_hhomeActionPerformed

    private void hbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hbookActionPerformed
        // TODO add your handling code here:
        dispose ();
        BOOK a=new BOOK ();
        a.show();
    }//GEN-LAST:event_hbookActionPerformed

    private void haccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_haccountActionPerformed

    private void haboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haboutActionPerformed
        // TODO add your handling code here:
        dispose ();
        ABOUT a=new ABOUT ();
        a.show();
    }//GEN-LAST:event_haboutActionPerformed

    private void rlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rlogoutActionPerformed
        // TODO add your handling code here:
        dispose ();
        REGIST x=new REGIST ();
        x.show();
    }//GEN-LAST:event_rlogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HOME().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton habout;
    private javax.swing.JButton haccount;
    private javax.swing.JButton hbook;
    private javax.swing.JButton hbus;
    private javax.swing.JButton hhome;
    private javax.swing.JButton hrefund;
    private javax.swing.JButton hservice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton rlogout;
    // End of variables declaration//GEN-END:variables
}
