/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
public class RESEND extends javax.swing.JFrame {

    /**
     * Creates new form RESEND
     */
    public RESEND() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bhome = new javax.swing.JButton();
        habout = new javax.swing.JButton();
        rlogout = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel1.setText("THANK YOU FOR CHOOSING US! ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, -10, 705, 122));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel2.setText("THE TICKET WILL BE RE-SENT IN NOT MORE THAN ONE MINUTE.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, 126));

        bhome.setBackground(new java.awt.Color(51, 255, 51));
        bhome.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        bhome.setText("HOME");
        bhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhomeActionPerformed(evt);
            }
        });
        getContentPane().add(bhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 109, 40));

        habout.setBackground(new java.awt.Color(255, 255, 0));
        habout.setText("ABOUT US");
        habout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                haboutActionPerformed(evt);
            }
        });
        getContentPane().add(habout, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 163, 47));

        rlogout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rlogout.setText("LOGOUT");
        rlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rlogoutActionPerformed(evt);
            }
        });
        getContentPane().add(rlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 530, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot 2024-01-26 141355.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 1340, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhomeActionPerformed
        // TODO add your handling code here:
        dispose ();
        HOME b=new HOME ();
        b.show();
    }//GEN-LAST:event_bhomeActionPerformed

    private void haboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haboutActionPerformed
        // TODO add your handling code here:
        dispose ();
        ABOUT a=new ABOUT ();
        a.show();
    }//GEN-LAST:event_haboutActionPerformed

    private void rlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rlogoutActionPerformed
        // TODO add your handling code here:
        dispose ();
        REGIST x=new REGIST ();
        x.show();
    }//GEN-LAST:event_rlogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RESEND.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RESEND.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RESEND.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RESEND.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RESEND().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bhome;
    private javax.swing.JButton habout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton rlogout;
    // End of variables declaration//GEN-END:variables
}
