/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
public class SEAT extends javax.swing.JFrame {

    /**
     * Creates new form SEAT
     */
    public SEAT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        savailable = new javax.swing.JLabel();
        sseat = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        bnext = new javax.swing.JButton();
        bnext1 = new javax.swing.JButton();
        stime1 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        bhome = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(153, 255, 0));
        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("THANK YOU FOR CHOOSING US, PLEASE CHOOSE YOUR FAVORITE BUS!");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 6, 795, 38));

        savailable.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        savailable.setForeground(new java.awt.Color(255, 255, 255));
        savailable.setText("AVAILABLE BUSES");
        getContentPane().add(savailable, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 142, 48));

        sseat.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        sseat.setForeground(new java.awt.Color(255, 255, 255));
        sseat.setText("SELECT SEAT");
        getContentPane().add(sseat, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 142, 49));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<<Please choose a bus>>", " ", "1. RITCO", "2. VIRUNGA", "3. KIGALI COACH", "4. VOLVANO", "5. INTERNATIONAL", "6. DIFFERENCE" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 82, -1, 48));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<<Please choose a seat>>", " ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 172, 172, 49));

        bnext.setText("PREVIOUS");
        bnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnextActionPerformed(evt);
            }
        });
        getContentPane().add(bnext, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 93, -1));

        bnext1.setText("NEXT");
        bnext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnext1ActionPerformed(evt);
            }
        });
        getContentPane().add(bnext1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 390, 93, -1));

        stime1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        stime1.setForeground(new java.awt.Color(255, 255, 255));
        stime1.setText("SELECT TIME");
        getContentPane().add(stime1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 142, 49));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<<Please choose time>>", " ", "04:30", "05:00", "05:30", "06:00", "06:30", "07:00", "07:30", "08:00", "08:30", "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00", " ", " " }));
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 247, 172, 49));

        bhome.setBackground(new java.awt.Color(51, 255, 51));
        bhome.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        bhome.setText("HOME");
        bhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhomeActionPerformed(evt);
            }
        });
        getContentPane().add(bhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(908, 7, 110, 38));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot 2024-01-26 141355.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 1030, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnextActionPerformed
        // TODO add your handling code here:
        dispose ();
        BOOK s=new BOOK ();
        s.show();
    }//GEN-LAST:event_bnextActionPerformed

    private void bnext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnext1ActionPerformed
        // TODO add your handling code here:
        dispose ();
        REVIEW q=new REVIEW ();
        q.show();
    }//GEN-LAST:event_bnext1ActionPerformed

    private void bhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhomeActionPerformed
        // TODO add your handling code here:
        dispose ();
        HOME b=new HOME ();
        b.show();
    }//GEN-LAST:event_bhomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SEAT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SEAT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SEAT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SEAT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SEAT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bhome;
    private javax.swing.JButton bnext;
    private javax.swing.JButton bnext1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel savailable;
    private javax.swing.JLabel sseat;
    private javax.swing.JLabel stime1;
    // End of variables declaration//GEN-END:variables
}
