/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
public class SERVICES extends javax.swing.JFrame {

    /**
     * Creates new form SERVICES
     */
    public SERVICES() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        bhome2 = new javax.swing.JButton();
        hbook = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jList1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "6.\tReliable Transportation:", "•\t\"Your journey, our commitment: reliable buses and taxis.\"", "•\t\"Trust in our fleet for secure and dependable travel.\"", " ", "7.\tOn-the-Go Convenience:", "•\t\"Book your ride anytime, anywhere with our mobile-friendly platform.\"", "•\t\"On-the-go travel made easy: buses and taxis at your fingertips.\"", " ", "8.\tCustomer-Centric Approach:", "•\t\"Customer satisfaction first: hassle-free bookings and refunds.\"", "•\t\"Our promise: customer-centric service from booking to refund.\"", " ", "9.\tFare Transparency:", "•\t\"No surprises! Transparent pricing and refund policies.\"", "•\t\"Fair fares, clear policies – experience the difference.\"", " ", "10.\tSecure and Safe:", "•\t\"Safety first! Choose our secure and reliable transportation services.\"", "•\t\"Travel with peace of mind: our commitment to safety.\"", " ", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 64, 490, 386));

        jList2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1.\tEffortless Booking:  ", "•\t\"Swiftly book buses, taxis, and more online!\"  ", "•\t\"Seamless online booking for buses, taxis, and moto vehicles.\"   ", " ", "2.\tFleet Variety: ", "•\t\"Diverse fleet – from buses to taxis and motorbikes.\"", " •\t\"Explore our range: buses, taxis, moto vehicles, and more!\"  ", " ", "3.\tRefund Assurance: ", "•\t\"Worry-free travel with our 30-minute refund policy.\" ", "•\t\"Cancel with confidence: hassle-free refunds within 30 minutes.\"  ", " ", "4.\tTime-Saving Solutions: ", "•\t\"Time matters! Book, ride, and cancel effortlessly.\" ", "•\t\"Efficient services, from booking to cancellation in minutes.\" ", " ", " 5.\tTransparent Process: ", "•\t\"Crystal-clear policies: refund within 30 minutes.\" ", "•\t\"See the difference with our transparent booking process.\" " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 64, 496, 386));

        jLabel1.setBackground(new java.awt.Color(102, 255, 204));
        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("WHAT WE OFFER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 6, 585, -1));

        bhome2.setBackground(new java.awt.Color(51, 255, 51));
        bhome2.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        bhome2.setText("HOME");
        bhome2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhome2ActionPerformed(evt);
            }
        });
        getContentPane().add(bhome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(905, 24, 110, -1));

        hbook.setBackground(new java.awt.Color(255, 255, 0));
        hbook.setText("BOOK A BUS");
        hbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hbookActionPerformed(evt);
            }
        });
        getContentPane().add(hbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 456, 124, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot 2024-01-26 141355.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1050, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bhome2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhome2ActionPerformed
        // TODO add your handling code here:
        dispose ();
        HOME b=new HOME ();
        b.show();
    }//GEN-LAST:event_bhome2ActionPerformed

    private void hbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hbookActionPerformed
        // TODO add your handling code here:
        dispose ();
        BOOK a=new BOOK ();
        a.show();
    }//GEN-LAST:event_hbookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SERVICES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SERVICES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SERVICES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SERVICES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SERVICES().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bhome2;
    private javax.swing.JButton hbook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
