
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
public class SIGNUP extends javax.swing.JFrame {

    /**
     * Creates new form SIGNUP
     */
    public SIGNUP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sfirstname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        slastname = new javax.swing.JTextField();
        semail = new javax.swing.JTextField();
        sgender = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        sretype = new javax.swing.JPasswordField();
        susername = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        spassword = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        signup = new javax.swing.JButton();
        slogin = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 153));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Username");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 403, 109, 38));

        jLabel7.setBackground(new java.awt.Color(0, 51, 51));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Gender");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 327, 109, 55));

        jPanel1.setBackground(new java.awt.Color(51, 255, 0));

        jLabel3.setBackground(new java.awt.Color(153, 0, 255));
        jLabel3.setFont(new java.awt.Font("Stencil", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("SIGN UP FORM");

        jLabel1.setFont(new java.awt.Font("Serif", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 255));
        jLabel1.setText("Fill your data in fields below");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("First name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 156, 135, 46));

        sfirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sfirstnameActionPerformed(evt);
            }
        });
        getContentPane().add(sfirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 159, 299, 43));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Last name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 231, 135, -1));

        slastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slastnameActionPerformed(evt);
            }
        });
        getContentPane().add(slastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 221, 299, 42));
        getContentPane().add(semail, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 272, 299, 43));

        sgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<<Choose your gender>>", "Male", "Female", "Rather not to say", " " }));
        sgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sgenderActionPerformed(evt);
            }
        });
        getContentPane().add(sgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 327, 299, 55));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 272, 115, 41));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Retype Password");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 543, 150, -1));
        getContentPane().add(sretype, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 531, 299, 46));
        getContentPane().add(susername, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 400, 299, 46));

        jLabel9.setBackground(new java.awt.Color(255, 51, 153));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Password");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 471, 150, 33));
        getContentPane().add(spassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 464, 299, 49));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel10.setText("Already a member?");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 649, 150, 27));

        signup.setBackground(new java.awt.Color(0, 0, 255));
        signup.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        signup.setForeground(new java.awt.Color(255, 255, 255));
        signup.setText("Signup");
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        getContentPane().add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 595, 140, -1));

        slogin.setBackground(new java.awt.Color(0, 0, 255));
        slogin.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        slogin.setForeground(new java.awt.Color(255, 255, 255));
        slogin.setText("Login");
        slogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sloginActionPerformed(evt);
            }
        });
        getContentPane().add(slogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 649, 140, -1));

        jPanel3.setBackground(new java.awt.Color(51, 255, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 770, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sfirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sfirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sfirstnameActionPerformed

    private void slastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_slastnameActionPerformed

    private void sgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sgenderActionPerformed

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
        // TODO add your handling code here:
        if(!sfirstname.getText().equals("")&& !slastname.getText().equals("")&& !semail.getText().equals("")) {
            String fn=sfirstname.getText();
            String ln=slastname.getText();
            String em=semail.getText();
            String ge=sgender.getSelectedItem().toString();
            String un=susername.getText();
            String ps=spassword.getText();
            String rp=sretype.getText();
            
           
            try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/java", "root", "");
//           Class.forName("com.mysql.cj.jdbc.Driver");
//            Connection con= DriverManager.getconnection("jdbc:mysql://localhost:3306/java","root","");
      System.out.println("connection Okay");
            PreparedStatement prep= null;
            
            prep= con.prepareStatement("insert into signup values (?,?,?,?,?,?)");
            prep.setString(1, fn);
            prep.setString(2, ln);
            prep.setString(3, em);
            prep.setString(4, ge);
            prep.setString(5, un);
            prep.setString(6, ps);
            if(prep.executeUpdate()>0){
                    JOptionPane.showMessageDialog(this, "REGISTRATION SUCCESSFULL");
                    dispose();
                    REGIST F =new REGIST ();
                    F.show();
                            
            }
            else{
                   JOptionPane.showMessageDialog(this, "OOPS! FAILED TO REGISTER");
            }


            }
            catch(Exception ex){
                System.out.println(ex+" action was not performed");
            }
            
        }
            
    }//GEN-LAST:event_signupActionPerformed

    private void sloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sloginActionPerformed
        // TODO add your handling code here:
        dispose ();
        REGIST l= new REGIST ();
        l.show();
    }//GEN-LAST:event_sloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SIGNUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SIGNUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SIGNUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SIGNUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SIGNUP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField semail;
    private javax.swing.JTextField sfirstname;
    private javax.swing.JComboBox<String> sgender;
    private javax.swing.JButton signup;
    private javax.swing.JTextField slastname;
    private javax.swing.JButton slogin;
    private javax.swing.JPasswordField spassword;
    private javax.swing.JPasswordField sretype;
    private javax.swing.JTextField susername;
    // End of variables declaration//GEN-END:variables
}
